name: 'Docs Report'
description: Create a report for Next.js documentation.
title: 'Docs: '
labels:
  - 'Documentation'
body:
  - type: markdown
    attributes:
      value: Before opening a new docs issue, is this something you can help us with? Your contributions are welcomed and appreciated. See our [Docs Contribution Guide](https://nextjs.org/docs/community/contribution-guide) to learn how to edit the Next.js docs.
  - type: markdown
    attributes:
      value: Thank you for helping us update our docs!
  - type: textarea
    attributes:
      label: What is the update you wish to see?
      description: 'Example: I would like to fix an example using the `<Link>` component. Or, the `<Link>` component docs are missing information.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: A clear description of any added context that might help us understand.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: 'Example: https://nextjs.org/docs/app/api-reference/components/link'
    validations:
      required: false
