blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/vercel/next.js/discussions
    about: Ask questions and discuss with other community members.
  - name: Feature request
    url: https://github.com/vercel/next.js/discussions/new?category=ideas
    about: Feature or docs requests should be opened as discussions.
  - name: Next.js Learn course
    url: https://github.com/vercel/next-learn/issues/new
    about: Next.js Learn course-related issues should be reported in their respective repository.
